package ua.stqa.pft.allo;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;

import java.util.HashMap;
import java.util.Map;
public class UsdTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeClass
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterClass
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void usd() {
    // Test name: usd
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://ru.investing.com/");
    // 2 | setWindowSize | 516x901 |  | 
    driver.manage().window().setSize(new Dimension(516, 901));
    // 3 | type | css=.searchText | usd | 
    driver.findElement(By.cssSelector(".searchText")).sendKeys("usd");
    // 4 | sendKeys | css=.searchText | ${KEY_ENTER} | 
    driver.findElement(By.cssSelector(".searchText")).sendKeys(Keys.ENTER);
    // 5 | click | css=.js-inner-all-results-quote-item:nth-child(1) > .third |  | 
    driver.findElement(By.cssSelector(".js-inner-all-results-quote-item:nth-child(1) > .third")).click();
  }
}
